[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_borrowing_lending = "6aTvYtygQvbXrETCaRVTy2asdQzVf38msbmyPAmb62wz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
